services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "bot_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend_parser:
    build:
      context: .
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
    restart: always

volumes:
  postgres: