- name: Deploy APP
  hosts: "prod"
  remote_user: "user1"
  become: yes
  vars:
    compose_file: "docker-compose-deploy.yaml"
    project_dir: "/home/user1/bot_parser"
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Create Dir
      ansible.builtin.file:
        path: "/home/user1/bot_parser"  # Всегда используйте абсолютный путь!
        state: directory
        mode: '0755'                    # Права (опционально)
        owner: user1                    # Владелец (опционально)
        group: user1                    # Группа (опционально)
    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: "{{ compose_file }}"
        dest: "{{ project_dir }}/{{ compose_file }}"
        mode: '0644'
    - name: Deploy
      ansible.builtin.shell:
        docker-compose -f docker-compose-deploy.yaml up -d
