- name: Deploy db
  hosts: "prod"
  remote_user: "user1"
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Deploy app
      docker_container:
        name: backend
        image: atread/workflow_testing

