- name: Deploy db
  hosts: "prod"
  remote_user: "user1"
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
    #    - name: Install Docker Compose
    #      ansible.builtin.shell: |
    #        curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #        chmod +x /usr/local/bin/docker-compose
    #        args:
    #          executable: /bin/bash
    #        when: ansible_os_family == 'Debian'
    - name: Deploy app
      docker_container:
        name: backend
        image: atread/workflow_testing

