- name: Deploy APP
  hosts: "prod"
  remote_user: "user1"
  become: yes
  vars:
    compose_file: "docker-compose-deploy.yaml"
    project_dir: "/home/user1/bot_parser"
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Install docker-compose
      ansible.builtin.apt:
        name: docker-compose
        state: present
        update_cache: yes
    - name: Create Dir
      ansible.builtin.file:
        path: "/home/user1/bot_parser"
        state: directory
        mode: '0755'
        owner: user1
        group: user1
    - name: Set remote env variables
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "{{ item.key }}={{ item.value }}"
        state: present
      loop:
        - { key: "TG_BOT_TOKEN", value: "{{ lookup('env', 'TG_BOT_TOKEN') }}" }
        - { key: "TG_BOT_NAME", value: "{{ lookup('env', 'TG_BOT_NAME') }}" }
      no_log: true
    - name: Test variable access
      ansible.builtin.shell: |
        . /etc/environment
    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: "{{ compose_file }}"
        dest: "{{ project_dir }}/{{ compose_file }}"
        mode: '0644'
    - name: Deploy
      ansible.builtin.shell:
        docker-compose -f ./bot_parser/docker-compose-deploy.yaml up -d
