- name: Deploy db
  hosts: "prod"
  remote_user: "andrey"
  tasks:
    - name: deploy
      become: yes
      docker_container:
        name: database
        image: postgres
        restart_policy: always
        env:
          POSTGRES_DB: bot_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        healthcheck:
          test: [ "CMD", "pg_isready", "-U", "admin", "-d", "bot_db" ]
          interval: 5s
          timeout: 5s
          retries: 5

