- name: Deploy db
  hosts: "prod"
  remote_user: "user1"
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Copy files
      ansible.builtin.copy:
        src: ~/BotParser/docker-compose-deploy.yaml
        dest: ~/docker-compose-deploy.yaml
    - name: Deploy
      ansible.builtin.shell:
        docker-compose -f docker-compose-deploy.yaml up -d
