name: Check
on: [ push, pull_request ]
jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '23'
          distribution: 'oracle'
      - name: Run Maven Checkstyle
#        run: mvn checkstyle:check
#        run: mvn pmd:check
        run: mvn spotbugs:check
  test:
    needs: style
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '23'
          distribution: 'oracle'
      - name: Run Maven Tests
        run: mvn test
  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest
#  deploy:

